[supervisord]
nodaemon=true

[program:redis]
command=redis-server --save "" --appendonly no
autostart=true
autorestart=true

[program:searxng]
command=python3 -m searx.webapp
directory=/usr/local/searxng
autostart=true
autorestart=true